### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by ghost** [zhijiansd/ansible-k8s#1]
老哥你什么系统 ，你是不是截多了 7.5  需要改成ip addr|grep secondary|awk '{print $2}'|cut -c 1-13
1-15会把后面掩码截出来

建议把所有需要配置的ip 使用变量

**Comment by zhijiansd** [comment]
感谢，我是基于7.4版本的，正在学习ansible，对于变量的使用不是很熟，以后会有改进的
